#Shimeji-ee Configuration Options
#Mon Jun 29 18:45:14 PDT 2026
Filter=bicubic
Opacity=1.0
Breeding=false
MenuDPI=96
InteractiveWindows=Chat/Notepad/Friends/Windows Live Messenger
AlwaysShowShimejiChooser=false
Environment=generic
Scaling=1.0
ActiveShimeji=Shimeji
AlwaysShowInformationScreen=false
